api_platform:
  title: "Symfony REST API"
  description: "A Symfony API to manage an invoice app."
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    html: ["text/html"]
    multipart: ["multipart/form-data"]
  swagger:
    versions: [3]
