#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /api/login
  methods: ["POST"]
api_me:
  path: "/api/user/me"
  methods: ["GET"]
  defaults:
    _controller: '\App\Controller\UserController::currentUser'
    _api_resource_class: 'App\Entity\User'
    _api_collection_operation_name: "current_user"
